name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # runs daily at 12 AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          ### Meta
          API_BASE_URL: https://wakatime.com/api
          REPOSITORY: mostofa-faysal/mostofa-faysal  # <- replace with your GitHub repo
          ### Content
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿  # <-- this creates the gradient bars
          CODE_LANG: txt
          TIME_RANGE: last_7_days
          LANG_COUNT: 5
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: true
          ### Commit
          COMMIT_MESSAGE: "Updated WakaTime stats in README"
          TARGET_BRANCH: main
          TARGET_PATH: README.md
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@github.com
          AUTHOR_NAME: Mostofa Faysal
          AUTHOR_EMAIL: amfaymos@gmail.com
